
BEGIN;


CREATE TABLE IF NOT EXISTS public.cinema
(
    cinema_id integer NOT NULL,
    name character varying(100) NOT NULL,
    adress character varying(100) NOT NULL,
    PRIMARY KEY (cinema_id)
);

CREATE TABLE IF NOT EXISTS public.hall
(
    "number" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cinema_id integer NOT NULL,
    screen_size character varying NOT NULL,
    number_of_seats integer NOT NULL,
    PRIMARY KEY ("number")
);

CREATE TABLE IF NOT EXISTS public.movie
(
    movie_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cinema_id integer NOT NULL,
    title character varying(100) NOT NULL,
    rating integer NOT NULL,
    PRIMARY KEY (movie_id)
);

CREATE TABLE IF NOT EXISTS public.seat
(
    seat_id integer NOT NULL,
    "number" integer NOT NULL,
    "row" integer NOT NULL,
    seat_number integer NOT NULL,
    is_occupied boolean NOT NULL,
    PRIMARY KEY (seat_id)
);

CREATE TABLE IF NOT EXISTS public.session
(
    session_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    movie_id integer NOT NULL,
    "number" integer NOT NULL,
    "time" timestamp without time zone NOT NULL,
    cost integer NOT NULL,
    PRIMARY KEY (session_id)
);

ALTER TABLE public.hall
    ADD FOREIGN KEY (cinema_id)
    REFERENCES public.cinema (cinema_id)
    NOT VALID;


ALTER TABLE public.movie
    ADD FOREIGN KEY (cinema_id)
    REFERENCES public.cinema (cinema_id)
    NOT VALID;


ALTER TABLE public.seat
    ADD FOREIGN KEY ("number")
    REFERENCES public.hall ("number")
    NOT VALID;


ALTER TABLE public.session
    ADD FOREIGN KEY (movie_id)
    REFERENCES public.movie (movie_id)
    NOT VALID;


ALTER TABLE public.session
    ADD FOREIGN KEY ("number")
    REFERENCES public.hall ("number")
    NOT VALID;

END;